# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_user }}"
    password: "{{ docker_registry_pass }}"
    reauthorize: yes

- name: Copy ovn-central systemd service
  template:
    src: ../services/ovn-central.service
    dest: /etc/systemd/system/ovn-central.service

- name: Start ovn-central systemd service
  systemd:
    name: ovn-central.service
    daemon_reload: yes
    state: started
    enabled: yes

- name: Copy postgres-db systemd service
  template:
    src: ../services/postgres-db.service
    dest: /etc/systemd/system/postgres-db.service

- name: Start postgres systemd service
  systemd:
    name: postgres-db.service
    daemon_reload: yes
    state: started
    enabled: yes

- name: Copy ovn-domain-isolation systemd service
  template:
    src: ../services/ovn-domain-isolation.service
    dest: /etc/systemd/system/ovn-domain-isolation.service

- name: Start ovn-domain-isolation systemd service
  systemd:
    name: ovn-domain-isolation.service
    daemon_reload: yes
    state: started
    enabled: yes
