# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Attatch OVS ports to br-int and bind interfaces to OVN
  block:
  - name: Set VF representor up
    ansible.builtin.shell: ip link set dev {{ item }} up
    loop: "{{ vf_representors.split(',') }}"

  - name: Pause for 15 seconds
    ansible.builtin.pause:    seconds=15

  - name: Connect Port to OVS Bridge br-int
    openvswitch.openvswitch.openvswitch_port:
      bridge: br-int
      port: '{{item.0}}'
      state: present
      set:
        - Interface '{{item.0}}' external_ids:"iface-id={{ item.1 }}"
        - Interface '{{item.0}}' type=dpdk
        - Interface '{{item.0}}' options:"dpdk-devargs=0000:03:00.0,representor=vf[{{ idx }}],dv_xmeta_en=4,dv_flow_en=2"
      timeout: '{{ovs_timeout}}'
    loop: "{{ vf_representors.split(',') | zip(external_interface_ids.split(',')) | list }}"
    loop_control:
      index_var: idx

- name: Set MTU request for OVS interfaces
  openvswitch.openvswitch.openvswitch_db:
    table: Interface
    record: "{{ item }}"
    col: mtu_request
    value: "{{ mtu }}"
  loop: "{{ vf_representors.split(',') | map('trim') | list }}"

- name: Restart OVS
  ansible.builtin.systemd: name=openvswitch-switch state=restarted
